package com.playposse.peertopeeroxygen.backend.serveractions;

import android.support.test.filters.MediumTest;
import android.support.test.runner.AndroidJUnit4;

import com.google.firebase.iid.FirebaseInstanceId;
import com.playposse.peertopeeroxygen.backend.peerToPeerOxygenApi.PeerToPeerOxygenApi;
import com.playposse.peertopeeroxygen.backend.peerToPeerOxygenApi.model.CompleteMissionDataBean;
import com.playposse.peertopeeroxygen.backend.peerToPeerOxygenApi.model.DomainBean;
import com.playposse.peertopeeroxygen.backend.peerToPeerOxygenApi.model.MasterUserBean;
import com.playposse.peertopeeroxygen.backend.peerToPeerOxygenApi.model.MissionLadderBean;
import com.playposse.peertopeeroxygen.backend.serveractions.util.AbstractServerActionTest;
import com.playposse.peertopeeroxygen.backend.serveractions.util.ApiTestUtil;
import com.restfb.types.TestUser;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.IOException;
import java.util.List;

import static junit.framework.Assert.assertEquals;
import static junit.framework.Assert.assertNotNull;
import static junit.framework.Assert.assertTrue;

/**
 * An API test for SaveMissionLadderServerAction.
 */
@RunWith(AndroidJUnit4.class)
@MediumTest
public class SaveMissionLadderServerActionTest extends AbstractServerActionTest {

    private static final String MISSION_LADDER_NAME = "Generated mission ladder";
    private static final String MISSION_LADDER_DESCRIPTION = "Autogenerated. DO NOT USE!";
    private static final String MINOR_CHANGE =" minor change";

    @Test
    public void createMissionLadder() throws IOException {
        createTestMissionLadder();
    }

    private MissionLadderBean createTestMissionLadder() throws IOException {
        MissionLadderBean missionLadderBean = new MissionLadderBean();
        missionLadderBean.setName(MISSION_LADDER_NAME);
        missionLadderBean.setDescription(MISSION_LADDER_DESCRIPTION);
        missionLadderBean.setDomainId(testDomainBean.getId());

        MissionLadderBean resultBean = api.saveMissionLadder(
                masterUserBean.getSessionId(),
                testDomainBean.getId(),
                missionLadderBean)
                .execute();

        assertNotNull(resultBean);
        assertNotNull(resultBean.getId());
        assertEquals(MISSION_LADDER_NAME, resultBean.getName());
        assertEquals(MISSION_LADDER_DESCRIPTION, resultBean.getDescription());
        assertEquals(testDomainBean.getId(), resultBean.getDomainId());

        missionLadderBean.setId(resultBean.getId());
        verifyMissionLadder(missionLadderBean);

        return resultBean;
    }

    @Test
    public void updateMissionLadder() throws IOException {
        MissionLadderBean missionLadderBean = createTestMissionLadder();

        missionLadderBean.setName(MISSION_LADDER_NAME + MINOR_CHANGE);
        missionLadderBean.setDescription(MISSION_LADDER_DESCRIPTION + MINOR_CHANGE);

        MissionLadderBean resultBean = api.saveMissionLadder(
                masterUserBean.getSessionId(),
                testDomainBean.getId(),
                missionLadderBean)
                .execute();
        verifyMissionLadder(missionLadderBean);

        assertNotNull(resultBean);
        assertNotNull(resultBean.getId());
        assertEquals(MISSION_LADDER_NAME + MINOR_CHANGE, resultBean.getName());
        assertEquals(MISSION_LADDER_DESCRIPTION + MINOR_CHANGE, resultBean.getDescription());
        assertEquals(testDomainBean.getId(), resultBean.getDomainId());
    }

    @Test
    public void deleteMissionLadder() throws IOException {
        MissionLadderBean missionLadderBean = createTestMissionLadder();

        api.deleteMissionLadder(
                masterUserBean.getSessionId(),
                missionLadderBean.getId(),
                testDomainBean.getId())
                .execute();
        verifyZeroMissionLadders();
    }

    private void verifyMissionLadder(MissionLadderBean expectedLadder) throws IOException {
        CompleteMissionDataBean completeMissionDataBean =
                api.getMissionData(masterUserBean.getSessionId(), testDomainBean.getId()).execute();
        List<MissionLadderBean> missionLadderBeans =
                completeMissionDataBean.getMissionLadderBeans();

        assertNotNull(missionLadderBeans);
        assertEquals(1, missionLadderBeans.size());

        MissionLadderBean actualLadder = missionLadderBeans.get(0);
        assertEquals(expectedLadder.getId(), actualLadder.getId());
        assertEquals(expectedLadder.getName(), actualLadder.getName());
        assertEquals(expectedLadder.getDescription(), actualLadder.getDescription());
        assertEquals(expectedLadder.getDomainId(), actualLadder.getDomainId());
    }

    private void verifyZeroMissionLadders() throws IOException {
        CompleteMissionDataBean completeMissionDataBean =
                api.getMissionData(masterUserBean.getSessionId(), testDomainBean.getId()).execute();
        List<MissionLadderBean> missionLadderBeans =
                completeMissionDataBean.getMissionLadderBeans();
        assertTrue((missionLadderBeans == null) || (missionLadderBeans.size() == 0));
    }
}
